CREATE TABLE Users(id SERIAL PRIMARY KEY, username TEXT UNIQUE NOT NULL, password TEXT NOT NULL, admin BOOLEAN, timestamp TIMESTAMP NOT NULL);
CREATE TABLE Recipes(id SERIAL PRIMARY KEY, name TEXT NOT NULL, user_id INTEGER REFERENCES Users (id) ON DELETE CASCADE, difficulty INTEGER NOT NULL, active_time INTEGER NOT NULL, passive_time INTEGER NOT NULL, meal_type TEXT NOT NULL, timestamp TIMESTAMP NOT NULL);
CREATE TABLE Ingredients (id SERIAL PRIMARY KEY, recipe_id INTEGER REFERENCES Recipes (id) ON DELETE CASCADE, name TEXT NOT NULL, amount TEXT NOT NULL);
CREATE TABLE Instructions (id SERIAL PRIMARY KEY, recipe_id INTEGER REFERENCES Recipes (id) ON DELETE CASCADE, text TEXT);

CREATE TABLE Likes ( id SERIAL PRIMARY KEY, recipe_id INTEGER REFERENCES Recipes (id) ON DELETE CASCADE, user_id INTEGER REFERENCES Users (id) ON DELETE CASCADE, liked BOOLEAN, timestamp TIMESTAMP);

CREATE TABLE Comments(id SERIAL PRIMARY KEY, user_id INTEGER REFERENCES Users (id) ON DELETE CASCADE, recipe_id INTEGER REFERENCES Recipes (id) ON DELETE CASCADE, text TEXT, timestamp TIMESTAMP);
